[tools]
poetry = { version="latest", pyproject="{{ config_root }}/pyproject.toml" }
python = '3.13.3'



[tasks.package]
run = [
    'cd website && bun run generate',
    'cp data/LLCP2023.parquet website/.output/public/LLCP2023.parquet',
    'cp data/LLCP2023_desc.parquet website/.output/public/LLCP2023_desc.parquet'
]